#!/usr/bin/env bash
# Generate this host's secrets and write deploy/minipc/.env.
#
#   ./deploy/minipc/bootstrap-env.sh
#
# Two of the four values are born here and exist nowhere else: the database
# password (a fresh container, so nothing to match) and the signing secret.
# The signing secret is the one that is *shared* — the labeller signs blob
# URLs with it and this host verifies them — so it is generated here and has
# to be copied to the desktop's password manager afterwards.
#
# The Garage credential is created too, if the garage CLI is reachable. That
# is a read-only key of its own rather than a reused one: this is the only
# component a browser talks to, and a shared credential cannot be revoked
# without breaking whatever else holds it. If the CLI is not reachable the
# script says so and leaves placeholders rather than writing something that
# looks configured and is not.
#
# Where the catalog is goes in config.toml beside this file, not in .env:
# the blob server serves that file's default catalog, so switching it is an
# edit there and a restart. The file is written from the example if there is
# none yet.
#
#   GARAGE="docker exec -i garage /garage" ./deploy/minipc/bootstrap-env.sh
#
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
env_file="$here/.env"
config_file="$here/config.toml"
bucket=${STRATA_S3_BUCKET:-mydata}
key_name=${STRATA_KEY_NAME:-strata-serve}

# shellcheck source=garage.sh
source "$here/garage.sh"
garage=$(resolve_garage)

# Refuse rather than overwrite. The file holds the only copy of a running
# deployment's credentials, and regenerating them silently would leave a
# server that verifies signatures nobody makes.
if [ -e "$env_file" ]; then
    echo "$env_file already exists. Move it aside first if you mean to start over." >&2
    exit 1
fi

db_password=$(openssl rand -hex 24)
blob_secret=$(openssl rand -hex 32)

access_key="REPLACE_ME"
secret_key="REPLACE_ME"
note=""

if $garage status >/dev/null 2>&1; then
    echo "Garage: $garage"
    echo "Creating read-only Garage key '$key_name' on bucket '$bucket'..."
    # The secret prints once, at creation, and there is no way to ask for it
    # again — so it is captured here or not at all.
    created=$($garage key create "$key_name" 2>&1) || {
        echo "$created" >&2
        echo "Could not create the key. Leaving placeholders." >&2
        created=""
    }
    # Matched by shape rather than by label, so a change in how the CLI lays
    # its output out does not silently yield an empty credential.
    parsed_id=$(printf '%s' "$created" | grep -oE 'GK[0-9a-f]{24}' | head -1 || true)
    parsed_secret=$(printf '%s' "$created" | grep -oE '\b[0-9a-f]{64}\b' | head -1 || true)

    if [ -n "$parsed_id" ] && [ -n "$parsed_secret" ]; then
        access_key=$parsed_id
        secret_key=$parsed_secret
        $garage bucket allow --read "$bucket" --key "$key_name"
        echo "  granted read on $bucket to $access_key"
    else
        note="could not read the key out of '$garage key create' output"
        echo "  $note — leaving placeholders" >&2
    fi
else
    note="garage did not answer as '$garage'"
    echo "$note — leaving placeholders for the S3 credentials." >&2
    echo "If you reach it some other way, set GARAGE to that, minus any -t:" >&2
    echo "  GARAGE=\"docker exec -i <container> /garage\" $0" >&2
fi

umask 077
cat > "$env_file" <<EOF
# Generated by bootstrap-env.sh. This file is the only copy of these values.
#
# STRATA_BLOB_SECRET is shared: the labeller signs blob URLs with it and this
# host verifies them. Copy it into the desktop's password manager as
# 'strata-blob-secret'. A mismatch fails as a 403 on every image, which reads
# as a broken deployment rather than as a wrong string.
#
# Credentials only. Which catalog is served is config.toml's business.

STRATA_DB_PASSWORD=$db_password
STRATA_BLOB_SECRET=$blob_secret

STRATA_S3_ACCESS_KEY=$access_key
STRATA_S3_SECRET_KEY=$secret_key
EOF
chmod 600 "$env_file"

if [ ! -e "$config_file" ]; then
    sed "s/^s3_bucket = \"mydata\"/s3_bucket = \"$bucket\"/" \
        "$here/config.example.toml" > "$config_file"
    echo "Wrote $config_file from the example, serving bucket '$bucket'."
fi

echo
echo "Wrote $env_file (0600)."
echo
echo "Next:"
if [ "$access_key" = "REPLACE_ME" ]; then
    echo "  1. Fill STRATA_S3_ACCESS_KEY and STRATA_S3_SECRET_KEY with a"
    echo "     read-only key: garage key create $key_name"
    echo "                    garage bucket allow --read $bucket --key $key_name"
fi
echo "  - Copy the signing secret to the desktop's password manager:"
echo "      grep STRATA_BLOB_SECRET $env_file"
echo "  - Check $config_file names the catalog to serve"
echo "  - Start the index, then the blob server:"
echo "      docker compose -f $here/docker-compose.yml up -d catalog-db"
echo "      docker compose -f $here/docker-compose.yml up -d blobs"
echo "  - The database password is new. After strata-catalog copy, the desktop's"
echo "    'strata-catalog-db' entry needs it, for PGPASSWORD:"
echo "      grep STRATA_DB_PASSWORD $env_file"
echo "  - More catalogs later: $here/new-catalog.sh <name>"
