"""catalog

Revision ID: ce85e6e673a0
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ce85e6e673a0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotation_class",
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("label_set_id", sa.Integer(), nullable=False),
        sa.Column("class_name", sa.String(length=255), nullable=False),
        sa.UniqueConstraint("sample_id", "label_set_id", "class_name"),
    )
    with op.batch_alter_table("annotation_class", schema=None) as batch_op:
        batch_op.create_index(
            "ix_annotation_class_lookup", ["label_set_id", "class_name"], unique=False
        )

    op.create_table(
        "catalog_identity",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "label_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("schema", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("media", sa.String(length=32), nullable=False),
        sa.Column("subtype", sa.String(length=32), nullable=False),
        sa.Column("group_id", sa.String(length=255), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checksum"),
    )
    with op.batch_alter_table("sample", schema=None) as batch_op:
        batch_op.create_index("ix_sample_group", ["group_id"], unique=False)
        batch_op.create_index("ix_sample_subtype", ["media", "subtype"], unique=False)

    op.create_table(
        "annotation",
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("label_set_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["label_set_id"], ["label_set.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sample_id"], ["sample.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sample_id", "label_set_id"),
    )
    with op.batch_alter_table("annotation", schema=None) as batch_op:
        batch_op.create_index("ix_annotation_label_set", ["label_set_id", "state"], unique=False)

    op.create_table(
        "annotation_conflict",
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("label_set_id", sa.Integer(), nullable=False),
        sa.Column("kept_value", sa.JSON(), nullable=True),
        sa.Column("other_value", sa.JSON(), nullable=True),
        sa.Column("other_origin", sa.String(length=64), nullable=True),
        sa.Column(
            "noticed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["label_set_id"], ["label_set.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sample_id"], ["sample.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sample_id", "label_set_id"),
    )
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("label_set_id", sa.Integer(), nullable=False),
        sa.Column("query", sa.JSON(), nullable=True),
        sa.Column("val_ratio", sa.Float(), nullable=False),
        sa.Column("val_ratio_achieved", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["label_set_id"],
            ["label_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_table(
        "sample_collection",
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("collection", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["sample_id"], ["sample.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sample_id", "collection"),
    )
    with op.batch_alter_table("sample_collection", schema=None) as batch_op:
        batch_op.create_index("ix_sample_collection_name", ["collection"], unique=False)

    op.create_table(
        "dataset_member",
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("val", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sample_id"], ["sample.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dataset_id", "sample_id"),
    )
    with op.batch_alter_table("dataset_member", schema=None) as batch_op:
        batch_op.create_index("ix_dataset_member_val", ["dataset_id", "val"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_member", schema=None) as batch_op:
        batch_op.drop_index("ix_dataset_member_val")

    op.drop_table("dataset_member")
    with op.batch_alter_table("sample_collection", schema=None) as batch_op:
        batch_op.drop_index("ix_sample_collection_name")

    op.drop_table("sample_collection")
    op.drop_table("dataset")
    op.drop_table("annotation_conflict")
    with op.batch_alter_table("annotation", schema=None) as batch_op:
        batch_op.drop_index("ix_annotation_label_set")

    op.drop_table("annotation")
    with op.batch_alter_table("sample", schema=None) as batch_op:
        batch_op.drop_index("ix_sample_subtype")
        batch_op.drop_index("ix_sample_group")

    op.drop_table("sample")
    op.drop_table("label_set")
    op.drop_table("catalog_identity")
    with op.batch_alter_table("annotation_class", schema=None) as batch_op:
        batch_op.drop_index("ix_annotation_class_lookup")

    op.drop_table("annotation_class")
    # ### end Alembic commands ###
